// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG84Yqshb111HQdnGa-PB4anJNRqSDaO8',
    appId: '1:807521768320:web:2e2aff9c24d4d49868a765',
    messagingSenderId: '807521768320',
    projectId: 'otlobdriverapp-dd897',
    authDomain: 'otlobdriverapp-dd897.firebaseapp.com',
    storageBucket: 'otlobdriverapp-dd897.appspot.com',
    measurementId: 'G-8L0MK1K6S9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9PrivFAAa_AWmJ-Bns--8cMaKE8edCvg',
    appId: '1:807521768320:android:ba7bf9eeb433015d68a765',
    messagingSenderId: '807521768320',
    projectId: 'otlobdriverapp-dd897',
    storageBucket: 'otlobdriverapp-dd897.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFpGjkTUWwBrva2I8ztoN4fRElXaVybyo',
    appId: '1:807521768320:ios:e21a04556d05010a68a765',
    messagingSenderId: '807521768320',
    projectId: 'otlobdriverapp-dd897',
    storageBucket: 'otlobdriverapp-dd897.appspot.com',
    iosClientId: '807521768320-cgoiv8bcaokdsam83bh1fuu3rm97d4pk.apps.googleusercontent.com',
    iosBundleId: 'com.store.otlob',
  );
}
